### ISSUE TITLE
Disable/Remove zfs-auto-snapshot 

### ISSUE THREAD

**Issue by xflou** [zfsonlinux/zfs-auto-snapshot#57] opened 2016-09-18 21:01 UTC
Hello,

Was not sure where to post this question. 

I was looking for a way to disable "zfs-auto-snapshot" on one of my systems(ubuntu).

I have set the following zfs parameters, but it does not seem to work:
"zfs set com.sun:auto-snapshot=false  pool/dataset"

I also commented out lines in the cron directories:

# exec zfs-auto-snapshot --quiet --syslog --label=daily --keep=31 //
# exec zfs-auto-snapshot --quiet --syslog --label=hourly --keep=24 //
# exec zfs-auto-snapshot --quiet --syslog --label=monthly --keep=12 //
# exec zfs-auto-snapshot --quiet --syslog --label=weekly --keep=8 //
# */15 * * * * root zfs-auto-snapshot --quiet --syslog --label=frequent --keep=4  //

Am I missing some other parameters and or Is there a better way to turn these off?

Thanks!

**Comment by kpande** [comment] 2016-09-18 21:26
sorry, not a bug. please use mailing list.

**Comment by xflou** [comment] 2016-09-18 21:53
Got it!

**Comment by xflou** [comment] 2016-09-18 21:56
Do you happen to have the link to join the mailing list? Thanks!

**Comment by kpande** [comment] 2016-09-18 23:11
it's @ list.zfsonlinux.org - can you then close the issue? thx

**Closed** 2016-09-19 00:50 UTC
